version: "3.8"
services:
  rustdesk-api-server:
    container_name: rustdesk-api-server
    build:
      context: .
    environment:
      - HOST=0.0.0.0
      - TZ=Europe/Berlin
      - CSRF_TRUSTED_ORIGINS=http://yourdomain.com:21114
      - LANG=de_DE.UTF-8 # Idee
    volumes:
      - /yourpath/db:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - "21114:21114"
    restart: unless-stopped
