# Generated by Django 4.2.16 on 2024-10-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rustdesdevice_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rustdesdevice',
            options={'ordering': ('-rid',), 'verbose_name': 'Gerät', 'verbose_name_plural': 'Geräteliste'},
        ),
        migrations.AlterModelOptions(
            name='rustdeskpeer',
            options={'ordering': ('-username',), 'verbose_name': 'Peers', 'verbose_name_plural': 'Peers-Liste'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktag',
            options={'ordering': ('-uid',), 'verbose_name': 'Tags', 'verbose_name_plural': 'Tag-Liste'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktoken',
            options={'ordering': ('-username',), 'verbose_name': 'Token', 'verbose_name_plural': 'Token-Liste'},
        ),
        migrations.AlterModelOptions(
            name='sharelink',
            options={'ordering': ('-create_time',), 'verbose_name': 'Freigabelink', 'verbose_name_plural': 'Linkliste'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')), 'verbose_name': 'Benutzer', 'verbose_name_plural': 'Benutzerliste'},
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Geräteregistrierungszeit'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='memory',
            field=models.CharField(max_length=100, verbose_name='Arbeitsspeicher'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='os',
            field=models.CharField(max_length=100, verbose_name='Betriebssystem'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='rid',
            field=models.CharField(blank=True, max_length=60, verbose_name='Client-ID'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Systembenutzername'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='version',
            field=models.CharField(max_length=100, verbose_name='Client-Version'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='alias',
            field=models.CharField(max_length=30, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='Betriebssystemname'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='platform',
            field=models.CharField(max_length=30, verbose_name='Plattform'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='rhash',
            field=models.CharField(max_length=60, verbose_name='Geräte-Verbindungspasswort'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='rid',
            field=models.CharField(max_length=60, verbose_name='Client-ID'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='tags',
            field=models.CharField(max_length=30, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='Benutzer-ID'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='username',
            field=models.CharField(max_length=20, verbose_name='Systembenutzername'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='tag_color',
            field=models.CharField(blank=True, max_length=60, verbose_name='Tag-Farbe'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='tag_name',
            field=models.CharField(max_length=60, verbose_name='Tag-Name'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='Zugehörige Benutzer-ID'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=60, verbose_name='Zugriffstoken'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Login-Zeit'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='Benutzer-ID'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='username',
            field=models.CharField(max_length=20, verbose_name='Benutzername'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='uuid',
            field=models.CharField(max_length=60, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeit'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Ist abgelaufen'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Wird verwendet'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='peers',
            field=models.CharField(max_length=20, verbose_name='Maschinen-ID-Liste'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='shash',
            field=models.CharField(max_length=60, verbose_name='Verknüpfungs-Schlüssel'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='Benutzer-ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deviceInfo',
            field=models.TextField(blank=True, verbose_name='Login-Informationen:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiviert'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Benutzername'),
        ),
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
                ('software_version', models.CharField(max_length=50)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rustdesdevice')),
            ],
            options={
                'verbose_name': 'Installierte Software',
                'verbose_name_plural': 'Installierte Software',
            },
        ),
    ]
